### ISSUE TITLE
allow invalidation of template cache fragments

### ISSUE THREAD

**Issue by evgenyfadeev** [coffin/coffin#30]
we need to invalidate template cache fragments sometimes.

so far we are doing it by copying the cache key calculation code and run invalidation on our side.

Is it possible to have something like  environment.clear_cache(*args) to guarantee that the same
cache key code is used for setting and invalidation of the cache?

Thanks!

**Comment by evgenyfadeev** [comment]
Would you take a pull request for a function to prepare the template fragment cache key?

**Comment by miracle2k** [comment]
I think so. Maybe make it a classmethod on the tag class.
