### ISSUE TITLE
django 1.7 chanages the HttpResponse constructor parameter name  mimetype to content_type

### ISSUE THREAD

**Issue by youngershen** [coffin/coffin#83]
django 1.7 change the  HttpResponse constructor parameter name mimetype to content_type as

     def __init__(self, content_type=None, status=None, reason=None):

so the conffin.shorts.render_to_response method raise an exception when you call to render the template , just change the mimetype to content_type

**Comment by seperman** [comment]
Any idea when is this release gonna happen?

**Comment by gregplaysguitar** [comment]
Active development appears to have stalled... maybe it needs to be handed over to someone else?

**Comment by mrooney** [comment]
+1 on a release to fix this for Django 1.7 :)

**Comment by miracle2k** [comment]
So I'm going to push a new release to PyPi, and it does appear as if this is fixed in master.
